# Generated by Django 4.2.2 on 2023-06-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('joined', models.DateTimeField(verbose_name='Player joined')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('votes', models.ImageField(default=0, upload_to='')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestats.player')),
            ],
        ),
    ]
